#!/bin/sh
#
# Configure /etc/jdktab containing java homes eg:
# 7:/opt/dev/jdk1.7.0_45
# 6:/opt/dev/jdk1.6.0_45
#
# Then configure the env eg
# JDK_NO=6
# $ . jdkenv 
# or
# . jdkenv
# to get the java home selection prompt.
#

JDKTAB=""

if [ -e /etc/jdktab ]; then
    JDKTAB=/etc/jdktab
elif [ -e /usr/local/etc/jdktab ]; then
    JDKTAB=/usr/local/etc/jdktab
else
    echo "No /etc/jdktab configured." 
    exit -1
fi

if [ -n "${JDKTAB}" ]; then

    #Prompt for the java home if noone selected.
    if [ -z "$JDK_NO" ]; then
        OPTIONS=""
        for line in `cat $JDKTAB`
        do
            echo $line
            OPTIONS=$OPTIONS${line%:*},
        done;
        OPTIONS=${OPTIONS%,*}
        read -p "Select the jdk for the env (eg $OPTIONS): " JDK_NO
    fi

    #Get the path to the new home from the config file.
    NEWPATH=$PATH
    NEW_JDK_HOME=""
    for line in `cat $JDKTAB`
    do
        if [ "${JDK_NO}" = "${line%:*}" ]; then
            NEW_JDK_HOME="${line#*:}" 
        fi
    done;

    REPLACED=""
    #Replace a jdk home already in the path with the new selection.
    #Remove all other jdk entries from the path.
    if [ -n "${NEW_JDK_HOME}" ]; then
        for line in `cat $JDKTAB`
        do
            if [ "$JDK_NO" != "${line%:*}" ]; then
                #Replace an old jdk with the new jdk exactly one
                #time and remove all other occurances.
                OLD_JDK_HOME=${line#*:}
                INPATH=`echo $PATH |grep $OLD_JDK_HOME`
                if ( [ -z "$REPLACED" ] &&  [ -n "$INPATH" ] ); then
                    NEWPATH=`echo $NEWPATH |sed s^${OLD_JDK_HOME}^${NEW_JDK_HOME}^`
                    REPLACED=y 
                fi
                NEWPATH=`echo $NEWPATH |sed s^:*${OLD_JDK_HOME}[^:]*^^g |sed s^:$^^g`
            else 
                #Be sure we only have one instance of the jdk we want in the PATH.
                OLD_JDK_HOME=${line#*:}
                NEWPATH=`echo $NEWPATH |sed s^${OLD_JDK_HOME}^XXXMARKERXX^`
                NEWPATH=`echo $NEWPATH |sed s^:*${OLD_JDK_HOME}[^:]*^^g |sed s^:$^^g`
                NEWPATH=`echo $NEWPATH |sed s^XXXMARKERXX^${NEW_JDK_HOME}^`
            fi
        done;

        #If the selected jdk is not in the path then add it.
        INPATH=`echo $NEWPATH |grep ${NEW_JDK_HOME}`
        if [ -z "${INPATH}" ]; then NEWPATH=${NEWPATH}:${NEW_JDK_HOME}/bin
        fi

    fi
    unset JDK_NO
    export JDK_NO
    PATH=$NEWPATH
    export PATH
    JAVA_HOME=$NEW_JDK_HOME
    export JAVA_HOME
fi


