#!/bin/sh
RADIO=$1

echo jazz24 hottomato

if [ "$RADIO" = "jazz24" ]; then
    mpv --cache=100 --playlist=http://icy1.abacast.com/kplu-jazz24aac-64.m3u

elif [ "$RADIO" = "hottomato" ]; then
    mpv http://playerservices.streamtheworld.com/api/livestream-redirect/GOL_HOTTOMATO.mp3
fi 
