#!/bin/bash
# Maintained at: git@github.com:dareni/shellscripts.git
#Set the current xterm title.

#In .bashrc:
#alias tcmd='. tcmd'
#export TCMD=$$
#export PS1='\[\033]0;$TCMD \u@\h: \w\007\]\[\033[22;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
if [ "$TERM" == "alacritty" ]; then
  echo -e "\e]2;$1"
else
  export TCMD="$1"
fi
