#!/bin/sh
### BEGIN INIT INFO
# Short-Description: Hardware temperature monitor.
# Description: Hardware temperature monitor.
# Provides: entry: tempsd
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Sysv script with systemd support: run initSystemd.
#
# A temperature monitor with shutdown when configured limits are exceeded.
# Simple configuration / extension for different sensors. Run sensors-detect
# to install the necessary drivers. Run sensors and determine what to monitor.
#
# If you have to, use `tempsd initSystemd` to config.
#
# See devTemp for a configuration example.


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=tempsd
if [ -d /run ]; then
  PIDFILE=/run/$NAME.pid
else
  PIDFILE=/var/run/$NAME.pid
fi
DESC="Hardware temperature monitor."
CONFIG=/usr/local/etc/tempsd.cfg
LOG=/var/log/tempsd.log
DEBUG_LOG=/tmp/tempsd.debug
CHECKLOOP=120
STARTUP_ERROR=0
ERROR=""
STX="^B"
ETX="^C"
WARNING_COUNT=2;
SYSTEMD_SERVICE=/etc/systemd/system/tempsd.service
SCRIPT_LOC=`readlink -f "$0"`
SCRIPT_PATH=${SCRIPT_LOC%/*}

if [ -n "${ARRAYS_ENV}" ]; then
  . "${ARRAYS_ENV}/array.env"
else
  . $SCRIPT_PATH/array.env
fi

#To enable systemd debug edit Environment DEBUG setting
#in /etc/systemd/system/tempsd.service
if [ -z "$DEBUG" ]; then
  DEBUG=0;
fi

debug() {
  if [ "$DEBUG" -eq 1 ]; then
    TSTAMP=`date +%M:%S`
    echo $TSTAMP $1 >>$DEBUG_LOG
  fi
}

if [ "$DEBUG" -eq 0 ]; then
  rm -f $DEBUG_LOG
else
  debug "Debug Enabled"
  echo "Debug Enabled $DEBUG_LOG" >> $LOG
fi

## Sources of temperature data (Raw output dumped on overheat event) ##########
getNvidiaOp() {
  RET=0
  nvCmd=`which nvidia-settings`
  if [ -n "$nvCmd" -a -e "$nvCmd" ];  then
    nvidia-settings -t -q $1/GPUCoreTemp
  else
    ERROR="Nonexistent nvidia-settings command."
    RET=1
  fi
  return $RET
}

getSensorOp() {
  sensors
}

getParams() {
  OIFS=$IFS
  IFS="_"
  for param in $1
  do
    tparam=`echo $param | sed 's/[\x00\x09\x0a\x0d\x0e\x0f]//g'`
    array_add params "$tparam"
  done
  IFS=$OIFS
}

## Possible check functions (extend here) #####################################
#Calls to these functions are specified in the config file ie
# the name of the func + args delimited by '_' and the max temp
# delimited by ':'. Function calls are delimited by ';' eg:
# temp_1:45;temp_2:45;nvidiaQuadro_0:70'
# Functions must set the TEMP variable.
#nvidiaQuadro_0 -> 0 defines the x11 display number.
#temp_1 -> 1 defines the temperature temp1 from 'sensors' output.

##devTemp is the default function
# arg1: device name; arg2 temperature name; arg3: position number of the temp.
# config eg:
#    devTemp_coretemp-isa-0000_Package id 0_4:40;devTemp_coretemp-isa-0000_Core 0_3:40
#
# for sensor output:
#           coretemp-isa-0000
#           Adapter: ISA adapter
#           Package id 0:  +34.0°C  (high = +82.0°C, crit = +102.0°C)
#           Core 0:        +29.0°C  (high = +82.0°C, crit = +102.0°C)
#
getDevTemp() {
  getParams "$1"
  paramCount=`array_size params`
  if [ $paramCount -lt 3 ]; then
    echo "ERROR: DevTemp requires 3 parameters but has $paramCount." >>$LOG
  else
    DEVICENAME=`get_avar params 1`
    TEMPNAME=`get_avar params 2`
    FIELDPOS=`get_avar params 3`
    array_clear params
    debug "devicename:$DEVICENAME tempname:$TEMPNAME field:$FIELD"
    TEMP=`sensors | \
    awk -v fi=$FIELDPOS -v devName="^$DEVICENAME" -v tempName="^$TEMPNAME" ' \
      BEGIN{found=0}
      {
        if ( $0 ~ /^$/) {
          found=0
        } else if (found == 0) {
          if ($0 ~ devName) {
            found=1
          }
        } else if (found==1) {
          if ($0 ~ tempName) {
            print $fi
          }
        }
      }'`
    debug "devTemp:$TEMP"
    TEMP=`echo $TEMP| cut -d + -f 2`
    TEMP=`echo $TEMP| cut -d . -f 1`
  fi
}

#moboTemp
getMoboTemp() {
  TEMP=`sensors | grep "MB Temperature" |awk '{print $3}'`
  TEMP=`echo $TEMP| cut -d + -f 2`
  TEMP=`echo $TEMP| cut -d . -f 1`
}
#cpuTemp
getCpuTemp() {
  TEMP=`getSensorOp | grep "CPU Temperature" |awk '{print $3}'`
  TEMP=`echo $TEMP| cut -d + -f 2`
  TEMP=`echo $TEMP| cut -d . -f 1`
}
#temp_?
getTemp() {
  #example "temp1:        +44.0°C"
  TEMP=`getSensorOp | grep "temp${1}:" | awk '{print $2}'`
  TEMP=`echo $TEMP| cut -d + -f 2`
  TEMP=`echo $TEMP| cut -d . -f 1`
  #TEMP=${TEMP#+}
  #TEMP=${TEMP%.*}
}

getRadeon() {
  TEMP=`sensors | \
  awk -v num="$1" 'BEGIN{found=0}
    { if ($0 ~ /^radeon-pci/) {found=1}
        if ( $0 ~ /^$/) {found=0}
          if (found==1) {
                if ($0 ~ /^temp1/){print $2}
                  }
    }'`
  TEMP=`echo $TEMP| cut -d + -f 2`
  TEMP=`echo $TEMP| cut -d . -f 1`
}

#nvidiaQuadro_DISPLAYNO
getNvidiaQuadro() {
  DISPLAY=:$1
  RET=0
  export DISPLAY
  xhost >/dev/null 2>/dev/null
  X_EXISTS=$?
  if [ $X_EXISTS -eq 0 ]; then
    TMP=`getNvidiaOp :$DISPLAY`
    RET=$?
    debug "getNvidiaQuadro TMP:$TMP RET:$RET"
    if [ $RET -eq 0 ]; then
      TEMP=`echo $TMP |cut -f1 -d' '`
      debug "getNvidiaQuadro TEMP:$TEMP"
    fi
  else
    TEMP="NO_X"
  fi
  return $RET
}

getK10temp() {
  TEMP=`sensors | \
  awk -v num="$1" 'BEGIN{found=0}
    {
      if ( $0 ~ /^$/) {
        found=0
      } else if (found == 0) {
        if ($0 ~ /^k10temp-pci/) {found=1}
      } else if (found==1) {
        if ($0 ~ /^Adapter/){found=2}
      } else if (found==2) {
        if ($0 ~ /^temp1/){
          print $2
        }
      }

    }'`
  TEMP=`echo $TEMP| cut -d + -f 2`
  TEMP=`echo $TEMP| cut -d . -f 1`
}

## Main logic #################################################################
checkTemp() {
#Return OVER:t/fMESSAGE[STX]message[ETX] text else an error message.
  cfg_data=$1
  cfg_data_test=$2

 OIFS="$IFS"
 IFS=";"
 for sensor in  `echo "$cfg_data"`
 do
   array_add sensors "$sensor"
 done;
 IFS=$OIFS

  sensorNo=1
  while [ $sensorNo -le `array_size sensors` ];
  do
    sensor=`get_avar sensors $sensorNo`
    debug "checkTemp sensor: $sensor"
    msg=""
    OVER="f"
    limit=`echo $sensor | cut -s -d : -f 2`
    cmd=`echo $sensor | cut -s -d : -f 1`
    if [ -z "$cmd" -o -z "$limit" ]; then
      echo "Error in tempsd: Not of form 'sensorNameA_arg1_arg2:temperatureLimit;\
sensorNameB_arg1:tempLimit' Sensor data: $sensor " | tee >> $LOG
      RET=1;
    else
      debug "cmd:$cmd"
      firstLetter=`echo ${cmd} | cut -c 1 | tr [:lower:] [:upper:]`
      endCmd=`echo ${cmd} | cut -c 2- | cut -d_ -f 1`
      params=`echo ${cmd} | cut -d_ -f 2-`
      cmd=get$firstLetter$endCmd
      debug "cmd:$cmd params:$params"
      TEMP=""
      $cmd "$params"
      RET=$?
      temp=$TEMP
      debug "sensor:$sensor cmd:$cmd RET:$RET temp:$temp"
      if [ $RET != 0 ]; then
        debug "RET:$RET"
        msg="Failure in tempsd testing for SENSOR:$sensor"
      elif [ "$temp" = "NO_X" ]; then
        #if NO_X then X is not running and we can not get the nv card temp.
        #Without X nv card should not be hot so ignore nv card and continue.
        debug "No X11, so no nvidia temps."
      else
        if [ -z "$temp" ]; then
          msg="ERROR tempsd : No temperature returned from SENSOR:$sensor"
          if [ -n "$cfg_data_test" ]; then
            #On cfg_data_test ie startup. Allow print of config location.
            RET=1;
          else
            OVER=t;
          fi
        elif [ -z "$cfg_data_test" -a "$temp" -gt "$limit" ]; then
          msg="WARNING tempsd: Running hot! LIMIT:$temp SENSOR:$sensor"
          OVER=t;
        fi
      fi
    fi
    if [ $RET -ne 0 ]; then
      echo OVER${OVER}MESSAGE${STX}${msg}${ETX}
      return $RET
    elif [ "$OVER" =  t ]; then
      echo OVER${OVER}MESSAGE${STX}${msg}${ETX}
      return $RET
    fi
    sensorNo=$((sensorNo+1))
  done;
  echo OVER${OVER}MESSAGE${STX}${ETX}
}

doShutdown() {
  shutdown -h 0
}

shutdownWarning() {
  causeMsg=$1
  {
    echo Shutdown imminent!
    echo $causeMsg
  } | wall
  DISPLAY=$TEMPSD_DISPLAY
  debug DISPLAY: $DISPLAY
  export DISPLAY
  xhost >/dev/null 2>/dev/null
  X_EXISTS=$?
  if [ $X_EXISTS -eq 0 ]; then
    xterm -fa *courier* -fs 20  -bg red -fg black -maximized -T "Computer Temperature Monitor" -hold \
      -e echo "$causeMsg" & 2>>$LOG >>$LOG
  else
    echo No X11! Is /etc/X11/xinit/xinitrc or $HOME/.xinitrc configured? ie: xhost +si:localuser:root >>$LOG
  fi
  WARNING_COUNT=$((WARNING_COUNT-1));
  debug WARNING_COUNT=$WARNING_COUNT
}

start() {
  debug start
  RET=0;
  if [ -e "${PIDFILE}" ]; then
    echo $NAME already running: $PIDFILE exists.
    RET=1;
  else
    TEMPSD_DISPLAY=`head -1 $CONFIG`
    CFG_DATA=`tail -1 $CONFIG`
    debug ConfigLocation:$CONFIG
    debug "ConfigData:$CFG_DATA"
    if [ -z "$CFG_DATA" ]; then
      echo
      echo Error no config data in $CONFIG.
      echo For example set $CONFIG containing:
      echo ":0"
      echo "temp_1:49;temp_2:50;temp_3:30;nvidiaQuadro_0:70"
      STARTUP_ERROR=1
    else
      OP=$(checkTemp "$CFG_DATA" test 2>&1)
      RET=$?
      if [ $RET -ne 0 ]; then
        echo Error in tempsd config data in $CONFIG.
        echo $OP
        echo THE TEMPERATURE MONITOR FAILED TO START.
        echo OPEATION OF YOUR COMPUTER WITHOUT A TEMPERATURE MONITOR MAY RESULT IN A FIRE!
        STARTUP_ERROR=1
        RET=0
      fi
    fi
    if [ $STARTUP_ERROR -eq 1 ]; then
      WARNING_COUNT=20
    fi
    (
      while [ 1 -eq 1 ]; do
        if [ $STARTUP_ERROR -eq 1 ]; then
            shutdownWarning "Error on start of tempsd service. Computer may cause a fire."
        else
          #Capture all stdout and stderr and fail on random output.
          if [ "$DEBUG" -eq 1 ]; then
            CFG_DATA=`tail -1 $CONFIG`
            debug "ConfigData:$CFG_DATA"
          fi
          OP=$(checkTemp "$CFG_DATA" 2>&1)
          RET=$?
          if [ "$RET" -ne 0 ]; then
            shutdownWarning $OP
          else
            MATCH=`expr match "$OP" '\(^OVER[tf]MESSAGE'$STX'.*'$ETX'\)'`
            OVER=`expr substr  "$OP" 5 1`
            MSG=`expr substr "$OP" 14 1000`
            debug "match:$MATCH"
            debug "over:$OVER"
            debug "msg:$MSG"
            if [ -z "$MATCH" ]; then
              shutdownWarning "Error tempsd data collection. Data: $OP"
            elif [ "$OVER" != "f" ]; then
              shutdownWarning "Computer Overheating. Check the operation of fans, water pump etc. $MSG"
              {
              date >> $LOG
              getSensorOp >> $LOG
              getNvidiaOp $TPSD_DISPLAY >> $LOG
              } | tee -a $LOG | wall
            fi
          fi
        fi
        if [ $WARNING_COUNT -lt 0 ]; then
          doShutdown
        fi
        sleep $CHECKLOOP;
      done;
    )&
    echo $! > $PIDFILE
    echo Started $NAME ok.
  fi
  return $RET;
}

stop() {
  RET=0
  if [ -e "${PIDFILE}" ]; then
    if [ -r "${PIDFILE}" ]; then
      PID=`cat ${PIDFILE}`
      MSG=`kill -0 $PID`
      RET=$?
      if [ $RET -ne 0 ]; then
        echo $MSG
      else
        MSG=`kill -15 $PID`
        RET=$?
        if [ $RET -ne 0 ]; then
          echo $MSG
          echo Could not stop process $NAME pid: $PID.
        else
          rm ${PIDFILE}
          echo Stopped $NAME ok.
        fi
      fi
    else
      echo "No permission to read file ${PIDFILE}."
      RET=1;
    fi
  fi
  return $RET
}

initSystemd() {
  if [ -e $SYSTEMD_SERVICE ]; then
    echo $SYSTEMD_SERVICE already installed.
  else
    touch $SYSTEMD_SERVICE
    chmod 700 $SYSTEMD_SERVICE
    (
      cat <<EOF
[Unit]
Description=Local Host temperature shutdown monitor.

[Service]
Type=forking
ExecStart=$SCRIPT_LOC start
ExecStop=$SCRIPT_LOC stop
Environment=DEBUG=0
Environment=ARRAYS_ENV=${SCRIPT_PATH}
SuccessExitStatus=0
RestartPreventExitStatus=1 2
PIDFile=$PIDFILE

[Install]
WantedBy=multi-user.target
EOF
    ) > $SYSTEMD_SERVICE
    systemctl enable tempsd.service
    systemctl start tempsd.service
  fi
}

case "$1" in
start)
  echo Starting $NAME...
  start
  ;;
stop)
  echo Stopping $NAME...
  stop
  ;;
restart)
  echo Restarting $NAME...
  stop
  start
  ;;
initSystemd)
  echo Installing $SYSTEMD_SERVICE
  initSystemd
  ;;
*)
  echo "Usage /etc/init.d/$NAME {start|stop|initSystemd}"
  exit 2;
  ;;
esac

# vim: tabstop=2 shiftwidth=2 expandtab:
