#!/bin/sh
# Maintained at: git@github.com:dareni/shellscripts.git

# Restart a vm on resume from suspend.
# A restart will set the correct time on the guest when the guest extensions
# are not installed.
#
# Copy the script containing the user and vm name ie:
#
# vboxrestart-USER-VMNAME
#
# eg sudo cp ./vbox_restart_pm_utils /etc/pm/sleep.d/20_vboxrestart-root-hal


PATH=/sbin:/usr/sbin:/bin:/usr/bin
VBOXMANAGE=/usr/bin/vboxmanage

VBOXUSER=`echo $0 |awk -F- '{print $(NF-1)}'`
VBOXVM=`echo $0 |awk -F- '{print $(NF)}'`

restart() {
    STATUS=`service vbox-$VBOXUSER-$VBOXVM status`
    if [ "$STATUS" = running ]; then
        service vbox-$VBOXUSER-$VBOXVM restart
    fi
}


case "${1}" in
        hibernate|suspend)
		# nothing
                ;;
        resume|thaw)
                restart 
                ;;
esac

