" Maintained at: git@github.com:dareni/shellscripts.git
"the FreeBSD Security Team advises that VIM users
"use 'set nomodeline' in ~/.vimrc to avoid the possibility of trojaned
"text files.

"Note! middle mouse insert requires <SHIFT>

source $VIMRUNTIME/debian.vim
source $VIMRUNTIME/defaults.vim
set nocompatible	" Use Vim defaults (much better!)
set directory=~/.cache
set backupdir=~/.cache
set tabstop=2
set shiftwidth=2
set expandtab
set ic
set selectmode=mouse
"set nowrap
"set autoindent
"set cindent
set foldmethod=marker

set bs=indent,eol,start		" allow backspacing over everything in insert mode
set viminfo='20,<50,s10,h,n~/.cache/viminfo
set history=20
syntax on
set hlsearch

"vim network read/write bookmark/history disable.
:let g:netrw_dirhistmax=0
